#!/usr/bin/env bash
# reproduce_final_plots.sh -- re-run every evaluation behind the three paper figures.
#
# GENERATED by scripts/release/_build_manifest.py from the W&B runs that were actually plotted
# (one `run` line per bar; provenance in each comment and in final_plots_manifest.csv).
# Do not hand-edit commands -- regenerate.
#
# Figures reproduced (then drawn by scripts/release/plot_reproduced.py):
#   random_loc : random-predicate setting, 6 specs x N=8/16/32 x {DIFF-MA, DIFF-SA, STLPY-SA, Gradient}
#   team_spec  : CaTL team specs (Choice / Redundant) x N=8/16/32 x {DIFF-MA, STLPY-SA, STLPY-Global}
#   high_n     : Mixed spec, N=8..128, DIFF-MA vs STLPY-SA (success from the native/gs2.0 split,
#                TtR + plan time from uniform gs2.0 -- so N<=32 needs TWO runs per cell)
#
# CODE PIN: dbg-ach-loss @ d1f2aa2 (2026-07-12)
#   Every command below was checked against that commit's argparse. The runs themselves were
#   launched from ancestors of it (git hashes in the comments).
#
# PREREQS
#   conda activate gcbfplus   (GPU environment per the top-level README)
#   pretrained/DubinsCar/gcbf+/            the GCBF+ tracking controller (bundled)
#   diff_checkpoints/qkmvppvt/             the diffusion planner (bundled; loads without W&B)
#   Gurobi licence reachable               STLPY-SA / STLPY-Global rows (MILP)
#   GPU with >= 8 GB                       diffusion rows; N=128 peaks ~6.7 GB
#
# USAGE
#   bash scripts/release/reproduce_final_plots.sh                  # everything
#   FIGS="high_n" bash scripts/release/reproduce_final_plots.sh    # one figure (space-separated list)
#   ONLY=f0td1sgv bash scripts/release/reproduce_final_plots.sh    # one original run id
#   DRY_RUN=1 bash ...                                             # print the commands, run nothing
#   FORCE=1 bash ...                                               # re-run rows whose log exists
#   WANDB_ARGS="--wandb-log --wandb-tags repro" bash ...           # also log to YOUR W&B
#
# OUTPUT
#   Each row appends one line to pretrained/DubinsCar/gcbf+/test_log_repro_<id>.csv (test.py --log
#   with --test-log-suffix). A row whose log already exists is skipped, so the script is resumable.
#   Then:  python scripts/release/plot_reproduced.py --out-dir out_repro
#
# KNOWN LIMITS (read before trusting a diff against the paper)
#   * Gradient (ce_nl) arm of random_loc is NOT re-run by this script. Those 18 runs came from an
#     unpublished development commit (0274dda0) and the pinned code's
#     --planner accepts only {stlpy, diffusion, stlpy_global}. Their original commands are listed
#     as comments for the record; plot_reproduced.py draws those bars from the paper's recorded
#     numbers (manifest ref_* columns) and labels them "ref" in its provenance print.
#   * STLPY-SA arm of team_spec: the paper's bars come from older local test_log.csv rows (no W&B
#     run, pre "spec-v2" code, epi 5/10). The commands are reconstructed from the logged settings
#     and marked "best-effort"; on the pinned (spec-v2) code STLPY-SA scores differ, especially
#     on Choice (the W&B spec-v2 STLPY-SA runs are tabulated in scripts/release/README.md).
#   * Every cell is a single seed (--seed 1234 default); N>=64 high_n cells are epi=3. Expect
#     run-to-run variance of a few points on success, more on TtR.
#   * Runtime: STLPY rows are minutes-to-hours each (N=128 ~195 s/plan x 3 episodes x many replans);
#     STLPY-Global rows ~800 s/episode x 10. Diffusion rows are seconds-to-minutes per episode.

set -uo pipefail
cd "$(dirname "${BASH_SOURCE[0]}")/../.."          # repo root
FIGS="${FIGS:-random_loc team_spec high_n}"
LOG_DIR="pretrained/DubinsCar/gcbf+"
WANDB_ARGS="${WANDB_ARGS:-}"
PASS=(); FAIL=(); SKIP=()

want_fig () { case " $FIGS " in *" $1 "*) return 0;; *) return 1;; esac; }

# run <fig> <id> [KEY=VAL ...] -- <test.py args...>
run () {
  local fig="$1" id="$2"; shift 2
  local envs=(); while [ "$1" != "--" ]; do envs+=("$1"); shift; done; shift
  want_fig "$fig" || return 0
  [ -n "${ONLY:-}" ] && [ "$ONLY" != "$id" ] && return 0
  local log="$LOG_DIR/test_log_repro_${id}.csv"
  if [ -s "$log" ] && [ -z "${FORCE:-}" ]; then echo "[skip] $id -> $log exists"; SKIP+=("$id"); return 0; fi
  echo; echo "==> [$fig] $id"; echo "+ ${envs[*]} python test.py $* --test-log-suffix _repro_${id} ${WANDB_ARGS}"
  [ -n "${DRY_RUN:-}" ] && return 0
  # shellcheck disable=SC2086
  if env "${envs[@]}" python test.py "$@" --test-log-suffix "_repro_${id}" ${WANDB_ARGS}; then
    PASS+=("$id"); else FAIL+=("$id"); echo "!! FAILED $id"; fi
}


# ================================================================================================
# FIGURE random_loc  (plot_paper.py --figure random_loc_dubins)
# area-6, random predicate locations (--random-goals), epi 10 (Gradient: 5); Signal uses the
# crowded R=1.5 region runs; DIFF-SA = single-draw edm except the edm-bo8 cells; Loop DIFF-MA
# = no achievable guidance. Selection rules: plot_config.yaml -> random_loc_dubins.
# ================================================================================================
# Branch           N=8   DIFF-MA       <- gcbfplus-stl-test/wfr2ujm6 commit 8499d431 2026-07-05  (success=95.0 plan=0.19s TtR=1197)
run random_loc wfr2ujm6 -- --path ./pretrained/DubinsCar/gcbf+/ --area-size 6 --obs 0 --nojit-rollout --spec-len 15 --goal-sample-interval 20 --async-planner --ignore-on-finish --no-video --log --random-goals --traced-goals --change_goal_immediately --epi 10 -n 8 --spec m2branch2 --planner diffusion --diffusion-method edm-ma --wandb-run-id qkmvppvt --num_candidates 8
# Branch           N=8   DIFF-SA       <- gcbfplus-stl-test/yqmxqmht commit 8499d431 2026-07-06  (success=93.8 plan=0.15s TtR=960)
run random_loc yqmxqmht -- --path ./pretrained/DubinsCar/gcbf+/ --area-size 6 --obs 0 --nojit-rollout --spec-len 15 --goal-sample-interval 20 --async-planner --ignore-on-finish --no-video --log --random-goals --traced-goals --change_goal_immediately --epi 10 -n 8 --spec m2branch2 --planner diffusion --diffusion-method edm --wandb-run-id qkmvppvt
# Branch           N=8   STLPY-SA      <- gcbfplus-stl-test/ipz5w1ae commit 8499d431 2026-07-05  (success=86.2 plan=9.20s TtR=552)
run random_loc ipz5w1ae -- --path ./pretrained/DubinsCar/gcbf+/ --area-size 6 --obs 0 --nojit-rollout --spec-len 15 --goal-sample-interval 20 --async-planner --ignore-on-finish --no-video --log --random-goals --traced-goals --change_goal_immediately --epi 10 -n 8 --spec m2branch2 --planner stlpy
# Branch           N=8   Gradient      <- diff-mastl-test/c9gwoygz commit 0274dda0 2026-07-06  (success=47.5 plan=13.39s TtR=1479)
#   NOT RUN (ce_nl not in pinned code; bar drawn from manifest ref values):
#   run random_loc c9gwoygz -- --path ./pretrained/DubinsCar/gcbf+/ --epi 5 --area-size 6 --obs 0 --seed 1234 --nojit-rollout --spec-len 30 --goal-sample-interval 20 --async-planner --ignore-on-finish --no-video --log -n 8 --spec m2branch2 --planner ce_nl --random-goals
# Branch           N=16  DIFF-MA       <- gcbfplus-stl-test/ofgoih55 commit 8499d431 2026-07-05  (success=96.2 plan=4.87s TtR=1300)
run random_loc ofgoih55 -- --path ./pretrained/DubinsCar/gcbf+/ --area-size 6 --obs 0 --nojit-rollout --spec-len 15 --goal-sample-interval 20 --async-planner --ignore-on-finish --no-video --log --random-goals --traced-goals --change_goal_immediately --epi 10 -n 16 --spec m2branch2 --planner diffusion --diffusion-method edm-ma --wandb-run-id qkmvppvt --num_candidates 8 --achievable_guidance
# Branch           N=16  DIFF-SA       <- gcbfplus-stl-test/nk7anw5r commit 8499d431 2026-07-06  (success=88.1 plan=0.39s TtR=1090)
run random_loc nk7anw5r -- --path ./pretrained/DubinsCar/gcbf+/ --area-size 6 --obs 0 --nojit-rollout --spec-len 15 --goal-sample-interval 20 --async-planner --ignore-on-finish --no-video --log --random-goals --traced-goals --change_goal_immediately --epi 10 -n 16 --spec m2branch2 --planner diffusion --diffusion-method edm --wandb-run-id qkmvppvt --use_batched_sampling --num_candidates 8
# Branch           N=16  STLPY-SA      <- gcbfplus-stl-test/mm85t4es commit 8499d431 2026-07-05  (success=81.9 plan=18.47s TtR=640)
run random_loc mm85t4es -- --path ./pretrained/DubinsCar/gcbf+/ --area-size 6 --obs 0 --nojit-rollout --spec-len 15 --goal-sample-interval 20 --async-planner --ignore-on-finish --no-video --log --random-goals --traced-goals --change_goal_immediately --epi 10 -n 16 --spec m2branch2 --planner stlpy
# Branch           N=16  Gradient      <- diff-mastl-test/x3k7e7ky commit 0274dda0 2026-07-06  (success=42.5 plan=26.98s TtR=1489)
#   NOT RUN (ce_nl not in pinned code; bar drawn from manifest ref values):
#   run random_loc x3k7e7ky -- --path ./pretrained/DubinsCar/gcbf+/ --epi 5 --area-size 6 --obs 0 --seed 1234 --nojit-rollout --spec-len 30 --goal-sample-interval 20 --async-planner --ignore-on-finish --no-video --log -n 16 --spec m2branch2 --planner ce_nl --random-goals
# Branch           N=32  DIFF-MA       <- gcbfplus-stl-test/ekvaewct commit 8499d431 2026-07-05  (success=82.5 plan=11.27s TtR=1570)
run random_loc ekvaewct -- --path ./pretrained/DubinsCar/gcbf+/ --area-size 6 --obs 0 --nojit-rollout --spec-len 15 --goal-sample-interval 20 --async-planner --ignore-on-finish --no-video --log --random-goals --traced-goals --change_goal_immediately --epi 10 -n 32 --spec m2branch2 --planner diffusion --diffusion-method edm-ma --wandb-run-id qkmvppvt --num_candidates 8 --achievable_guidance
# Branch           N=32  DIFF-SA       <- gcbfplus-stl-test/y86ji76y commit 8499d431 2026-07-06  (success=75.0 plan=0.55s TtR=1383)
run random_loc y86ji76y -- --path ./pretrained/DubinsCar/gcbf+/ --area-size 6 --obs 0 --nojit-rollout --spec-len 15 --goal-sample-interval 20 --async-planner --ignore-on-finish --no-video --log --random-goals --traced-goals --change_goal_immediately --epi 10 -n 32 --spec m2branch2 --planner diffusion --diffusion-method edm --wandb-run-id qkmvppvt --use_batched_sampling --num_candidates 8
# Branch           N=32  STLPY-SA      <- gcbfplus-stl-test/81eddjhh commit 8499d431 2026-07-05  (success=63.7 plan=37.41s TtR=834)
run random_loc 81eddjhh -- --path ./pretrained/DubinsCar/gcbf+/ --area-size 6 --obs 0 --nojit-rollout --spec-len 15 --goal-sample-interval 20 --async-planner --ignore-on-finish --no-video --log --random-goals --traced-goals --change_goal_immediately --epi 10 -n 32 --spec m2branch2 --planner stlpy
# Branch           N=32  Gradient      <- diff-mastl-test/2d73qjdu commit 0274dda0 2026-07-06  (success=20.0 plan=52.64s TtR=1744)
#   NOT RUN (ce_nl not in pinned code; bar drawn from manifest ref values):
#   run random_loc 2d73qjdu -- --path ./pretrained/DubinsCar/gcbf+/ --epi 5 --area-size 6 --obs 0 --seed 1234 --nojit-rollout --spec-len 30 --goal-sample-interval 20 --async-planner --ignore-on-finish --no-video --log -n 32 --spec m2branch2 --planner ce_nl --random-goals
# Cover            N=8   DIFF-MA       <- gcbfplus-stl-test/xnzi219x commit 8499d431 2026-07-05  (success=97.5 plan=0.23s TtR=1295)
run random_loc xnzi219x -- --path ./pretrained/DubinsCar/gcbf+/ --area-size 6 --obs 0 --nojit-rollout --spec-len 15 --goal-sample-interval 20 --async-planner --ignore-on-finish --no-video --log --random-goals --traced-goals --change_goal_immediately --epi 10 -n 8 --spec mcover3 --planner diffusion --diffusion-method edm-ma --wandb-run-id qkmvppvt --num_candidates 8
# Cover            N=8   DIFF-SA       <- gcbfplus-stl-test/mw5f5nph commit 8499d431 2026-07-06  (success=93.8 plan=0.25s TtR=1020)
run random_loc mw5f5nph -- --path ./pretrained/DubinsCar/gcbf+/ --area-size 6 --obs 0 --nojit-rollout --spec-len 15 --goal-sample-interval 20 --async-planner --ignore-on-finish --no-video --log --random-goals --traced-goals --change_goal_immediately --epi 10 -n 8 --spec mcover3 --planner diffusion --diffusion-method edm --wandb-run-id qkmvppvt
# Cover            N=8   STLPY-SA      <- gcbfplus-stl-test/h5gtu4b6 commit 8499d431 2026-07-05  (success=91.2 plan=7.63s TtR=614)
run random_loc h5gtu4b6 -- --path ./pretrained/DubinsCar/gcbf+/ --area-size 6 --obs 0 --nojit-rollout --spec-len 15 --goal-sample-interval 20 --async-planner --ignore-on-finish --no-video --log --random-goals --traced-goals --change_goal_immediately --epi 10 -n 8 --spec mcover3 --planner stlpy
# Cover            N=8   Gradient      <- diff-mastl-test/qc0rgo0r commit 0274dda0 2026-07-06  (success=25.0 plan=15.54s TtR=1256)
#   NOT RUN (ce_nl not in pinned code; bar drawn from manifest ref values):
#   run random_loc qc0rgo0r -- --path ./pretrained/DubinsCar/gcbf+/ --epi 5 --area-size 6 --obs 0 --seed 1234 --nojit-rollout --spec-len 30 --goal-sample-interval 20 --async-planner --ignore-on-finish --no-video --log -n 8 --spec mcover3 --planner ce_nl --random-goals
# Cover            N=16  DIFF-MA       <- gcbfplus-stl-test/6dzdog5g commit 8499d431 2026-07-05  (success=98.8 plan=0.28s TtR=1415)
run random_loc 6dzdog5g -- --path ./pretrained/DubinsCar/gcbf+/ --area-size 6 --obs 0 --nojit-rollout --spec-len 15 --goal-sample-interval 20 --async-planner --ignore-on-finish --no-video --log --random-goals --traced-goals --change_goal_immediately --epi 10 -n 16 --spec mcover3 --planner diffusion --diffusion-method edm-ma --wandb-run-id qkmvppvt --num_candidates 8
# Cover            N=16  DIFF-SA       <- gcbfplus-stl-test/fmfvixbm commit 8499d431 2026-07-06  (success=88.1 plan=0.33s TtR=1143)
run random_loc fmfvixbm -- --path ./pretrained/DubinsCar/gcbf+/ --area-size 6 --obs 0 --nojit-rollout --spec-len 15 --goal-sample-interval 20 --async-planner --ignore-on-finish --no-video --log --random-goals --traced-goals --change_goal_immediately --epi 10 -n 16 --spec mcover3 --planner diffusion --diffusion-method edm --wandb-run-id qkmvppvt
# Cover            N=16  STLPY-SA      <- gcbfplus-stl-test/34kq1e8t commit 8499d431 2026-07-05  (success=85.0 plan=15.22s TtR=707)
run random_loc 34kq1e8t -- --path ./pretrained/DubinsCar/gcbf+/ --area-size 6 --obs 0 --nojit-rollout --spec-len 15 --goal-sample-interval 20 --async-planner --ignore-on-finish --no-video --log --random-goals --traced-goals --change_goal_immediately --epi 10 -n 16 --spec mcover3 --planner stlpy
# Cover            N=16  Gradient      <- diff-mastl-test/ew2te96l commit 0274dda0 2026-07-06  (success=20.0 plan=33.04s TtR=1410)
#   NOT RUN (ce_nl not in pinned code; bar drawn from manifest ref values):
#   run random_loc ew2te96l -- --path ./pretrained/DubinsCar/gcbf+/ --epi 5 --area-size 6 --obs 0 --seed 1234 --nojit-rollout --spec-len 30 --goal-sample-interval 20 --async-planner --ignore-on-finish --no-video --log -n 16 --spec mcover3 --planner ce_nl --random-goals
# Cover            N=32  DIFF-MA       <- gcbfplus-stl-test/suhk3eof commit 8499d431 2026-07-05  (success=89.1 plan=0.31s TtR=1633)
run random_loc suhk3eof -- --path ./pretrained/DubinsCar/gcbf+/ --area-size 6 --obs 0 --nojit-rollout --spec-len 15 --goal-sample-interval 20 --async-planner --ignore-on-finish --no-video --log --random-goals --traced-goals --change_goal_immediately --epi 10 -n 32 --spec mcover3 --planner diffusion --diffusion-method edm-ma --wandb-run-id qkmvppvt --num_candidates 8
# Cover            N=32  DIFF-SA       <- gcbfplus-stl-test/0xs6mde5 commit 8499d431 2026-07-06  (success=81.9 plan=0.38s TtR=1378)
run random_loc 0xs6mde5 -- --path ./pretrained/DubinsCar/gcbf+/ --area-size 6 --obs 0 --nojit-rollout --spec-len 15 --goal-sample-interval 20 --async-planner --ignore-on-finish --no-video --log --random-goals --traced-goals --change_goal_immediately --epi 10 -n 32 --spec mcover3 --planner diffusion --diffusion-method edm --wandb-run-id qkmvppvt
# Cover            N=32  STLPY-SA      <- gcbfplus-stl-test/11qmh3v5 commit 8499d431 2026-07-05  (success=67.5 plan=30.65s TtR=886)
run random_loc 11qmh3v5 -- --path ./pretrained/DubinsCar/gcbf+/ --area-size 6 --obs 0 --nojit-rollout --spec-len 15 --goal-sample-interval 20 --async-planner --ignore-on-finish --no-video --log --random-goals --traced-goals --change_goal_immediately --epi 10 -n 32 --spec mcover3 --planner stlpy
# Cover            N=32  Gradient      <- diff-mastl-test/jatnzwjs commit 0274dda0 2026-07-06  (success=17.5 plan=69.11s TtR=1847)
#   NOT RUN (ce_nl not in pinned code; bar drawn from manifest ref values):
#   run random_loc jatnzwjs -- --path ./pretrained/DubinsCar/gcbf+/ --epi 5 --area-size 6 --obs 0 --seed 1234 --nojit-rollout --spec-len 30 --goal-sample-interval 20 --async-planner --ignore-on-finish --no-video --log -n 32 --spec mcover3 --planner ce_nl --random-goals
# Loop             N=8   DIFF-MA       <- gcbfplus-stl-test/abqr1bv7 commit 8499d431 2026-07-05  (success=90.0 plan=0.33s TtR=1559)
run random_loc abqr1bv7 -- --path ./pretrained/DubinsCar/gcbf+/ --area-size 6 --obs 0 --nojit-rollout --spec-len 15 --goal-sample-interval 20 --async-planner --ignore-on-finish --no-video --log --random-goals --traced-goals --change_goal_immediately --epi 10 -n 8 --spec m2loop3 --planner diffusion --diffusion-method edm-ma --wandb-run-id qkmvppvt --num_candidates 8
# Loop             N=8   DIFF-SA       <- gcbfplus-stl-test/hnt9fp7p commit 8499d431 2026-07-06  (success=96.2 plan=0.76s TtR=1486)
run random_loc hnt9fp7p -- --path ./pretrained/DubinsCar/gcbf+/ --area-size 6 --obs 0 --nojit-rollout --spec-len 15 --goal-sample-interval 20 --async-planner --ignore-on-finish --no-video --log --random-goals --traced-goals --change_goal_immediately --epi 10 -n 8 --spec m2loop3 --planner diffusion --diffusion-method edm --wandb-run-id qkmvppvt --use_batched_sampling --num_candidates 8
# Loop             N=8   STLPY-SA      <- gcbfplus-stl-test/99lj2g6v commit 8499d431 2026-07-05  (success=88.8 plan=21.86s TtR=863)
run random_loc 99lj2g6v -- --path ./pretrained/DubinsCar/gcbf+/ --area-size 6 --obs 0 --nojit-rollout --spec-len 15 --goal-sample-interval 20 --async-planner --ignore-on-finish --no-video --log --random-goals --traced-goals --change_goal_immediately --epi 10 -n 8 --spec m2loop3 --planner stlpy
# Loop             N=8   Gradient      <- diff-mastl-test/6kw8qsda commit 0274dda0 2026-07-06  (success=37.5 plan=48.35s TtR=1544)
#   NOT RUN (ce_nl not in pinned code; bar drawn from manifest ref values):
#   run random_loc 6kw8qsda -- --path ./pretrained/DubinsCar/gcbf+/ --epi 5 --area-size 6 --obs 0 --seed 1234 --nojit-rollout --spec-len 30 --goal-sample-interval 20 --async-planner --ignore-on-finish --no-video --log -n 8 --spec m2loop3 --planner ce_nl --random-goals
# Loop             N=16  DIFF-MA       <- gcbfplus-stl-test/6gfjzl0m commit 8499d431 2026-07-05  (success=91.9 plan=0.38s TtR=1679)
run random_loc 6gfjzl0m -- --path ./pretrained/DubinsCar/gcbf+/ --area-size 6 --obs 0 --nojit-rollout --spec-len 15 --goal-sample-interval 20 --async-planner --ignore-on-finish --no-video --log --random-goals --traced-goals --change_goal_immediately --epi 10 -n 16 --spec m2loop3 --planner diffusion --diffusion-method edm-ma --wandb-run-id qkmvppvt --num_candidates 8
# Loop             N=16  DIFF-SA       <- gcbfplus-stl-test/o83xwls7 commit 8499d431 2026-07-06  (success=92.5 plan=1.11s TtR=1677)
run random_loc o83xwls7 -- --path ./pretrained/DubinsCar/gcbf+/ --area-size 6 --obs 0 --nojit-rollout --spec-len 15 --goal-sample-interval 20 --async-planner --ignore-on-finish --no-video --log --random-goals --traced-goals --change_goal_immediately --epi 10 -n 16 --spec m2loop3 --planner diffusion --diffusion-method edm --wandb-run-id qkmvppvt --use_batched_sampling --num_candidates 8
# Loop             N=16  STLPY-SA      <- gcbfplus-stl-test/woart9ay commit 8499d431 2026-07-05  (success=76.2 plan=44.81s TtR=1039)
run random_loc woart9ay -- --path ./pretrained/DubinsCar/gcbf+/ --area-size 6 --obs 0 --nojit-rollout --spec-len 15 --goal-sample-interval 20 --async-planner --ignore-on-finish --no-video --log --random-goals --traced-goals --change_goal_immediately --epi 10 -n 16 --spec m2loop3 --planner stlpy
# Loop             N=16  Gradient      <- diff-mastl-test/zo1nv2df commit 0274dda0 2026-07-06  (success=27.5 plan=103.35s TtR=1778)
#   NOT RUN (ce_nl not in pinned code; bar drawn from manifest ref values):
#   run random_loc zo1nv2df -- --path ./pretrained/DubinsCar/gcbf+/ --epi 5 --area-size 6 --obs 0 --seed 1234 --nojit-rollout --spec-len 30 --goal-sample-interval 20 --async-planner --ignore-on-finish --no-video --log -n 16 --spec m2loop3 --planner ce_nl --random-goals
# Loop             N=32  DIFF-MA       <- gcbfplus-stl-test/moecj314 commit 8499d431 2026-07-05  (success=80.9 plan=0.45s TtR=2107)
run random_loc moecj314 -- --path ./pretrained/DubinsCar/gcbf+/ --area-size 6 --obs 0 --nojit-rollout --spec-len 15 --goal-sample-interval 20 --async-planner --ignore-on-finish --no-video --log --random-goals --traced-goals --change_goal_immediately --epi 10 -n 32 --spec m2loop3 --planner diffusion --diffusion-method edm-ma --wandb-run-id qkmvppvt --num_candidates 8
# Loop             N=32  DIFF-SA       <- gcbfplus-stl-test/f8uowczc commit 8499d431 2026-07-06  (success=74.7 plan=1.44s TtR=2267)
run random_loc f8uowczc -- --path ./pretrained/DubinsCar/gcbf+/ --area-size 6 --obs 0 --nojit-rollout --spec-len 15 --goal-sample-interval 20 --async-planner --ignore-on-finish --no-video --log --random-goals --traced-goals --change_goal_immediately --epi 10 -n 32 --spec m2loop3 --planner diffusion --diffusion-method edm --wandb-run-id qkmvppvt --use_batched_sampling --num_candidates 8
# Loop             N=32  STLPY-SA      <- gcbfplus-stl-test/fyihbk9q commit 8499d431 2026-07-05  (success=52.2 plan=88.90s TtR=1454)
run random_loc fyihbk9q -- --path ./pretrained/DubinsCar/gcbf+/ --area-size 6 --obs 0 --nojit-rollout --spec-len 15 --goal-sample-interval 20 --async-planner --ignore-on-finish --no-video --log --random-goals --traced-goals --change_goal_immediately --epi 10 -n 32 --spec m2loop3 --planner stlpy
# Loop             N=32  Gradient      <- diff-mastl-test/nvnc5yu7 commit 0274dda0 2026-07-06  (success=11.2 plan=193.14s TtR=2214)
#   NOT RUN (ce_nl not in pinned code; bar drawn from manifest ref values):
#   run random_loc nvnc5yu7 -- --path ./pretrained/DubinsCar/gcbf+/ --epi 5 --area-size 6 --obs 0 --seed 1234 --nojit-rollout --spec-len 30 --goal-sample-interval 20 --async-planner --ignore-on-finish --no-video --log -n 32 --spec m2loop3 --planner ce_nl --random-goals
# Mixed            N=8   DIFF-MA       <- gcbfplus-stl-test/qz4o75na commit 8499d431 2026-07-05  (success=93.8 plan=3.38s TtR=1366)
run random_loc qz4o75na -- --path ./pretrained/DubinsCar/gcbf+/ --area-size 6 --obs 0 --nojit-rollout --spec-len 15 --goal-sample-interval 20 --async-planner --ignore-on-finish --no-video --log --random-goals --traced-goals --change_goal_immediately --epi 10 -n 8 --spec mseq3-m2branch2-mcover3-m2loop3-m2signal3 --planner diffusion --diffusion-method edm-ma --wandb-run-id qkmvppvt --num_candidates 8 --achievable_guidance
# Mixed            N=8   DIFF-SA       <- gcbfplus-stl-test/e45b3cnb commit 8499d431 2026-07-06  (success=93.8 plan=0.69s TtR=1360)
run random_loc e45b3cnb -- --path ./pretrained/DubinsCar/gcbf+/ --area-size 6 --obs 0 --nojit-rollout --spec-len 15 --goal-sample-interval 20 --async-planner --ignore-on-finish --no-video --log --random-goals --traced-goals --change_goal_immediately --epi 10 -n 8 --spec mseq3-m2branch2-mcover3-m2loop3-m2signal3 --planner diffusion --diffusion-method edm --wandb-run-id qkmvppvt
# Mixed            N=8   STLPY-SA      <- gcbfplus-stl-test/s4jdy6i3 commit 8499d431 2026-07-05  (success=81.2 plan=12.88s TtR=817)
run random_loc s4jdy6i3 -- --path ./pretrained/DubinsCar/gcbf+/ --area-size 6 --obs 0 --nojit-rollout --spec-len 15 --goal-sample-interval 20 --async-planner --ignore-on-finish --no-video --log --random-goals --traced-goals --change_goal_immediately --epi 10 -n 8 --spec mseq3-m2branch2-mcover3-m2loop3-m2signal3 --planner stlpy
# Mixed            N=8   Gradient      <- diff-mastl-test/po5yuceo commit 0274dda0 2026-07-06  (success=17.5 plan=28.70s TtR=1564)
#   NOT RUN (ce_nl not in pinned code; bar drawn from manifest ref values):
#   run random_loc po5yuceo -- --path ./pretrained/DubinsCar/gcbf+/ --epi 5 --area-size 6 --obs 0 --seed 1234 --nojit-rollout --spec-len 30 --goal-sample-interval 20 --async-planner --ignore-on-finish --no-video --log -n 8 --spec mseq3-m2branch2-mcover3-m2loop3-m2signal3 --planner ce_nl --random-goals
# Mixed            N=16  DIFF-MA       <- gcbfplus-stl-test/k2ccm9wx commit 8499d431 2026-07-05  (success=95.6 plan=6.57s TtR=1563)
run random_loc k2ccm9wx -- --path ./pretrained/DubinsCar/gcbf+/ --area-size 6 --obs 0 --nojit-rollout --spec-len 15 --goal-sample-interval 20 --async-planner --ignore-on-finish --no-video --log --random-goals --traced-goals --change_goal_immediately --epi 10 -n 16 --spec mseq3-m2branch2-mcover3-m2loop3-m2signal3 --planner diffusion --diffusion-method edm-ma --wandb-run-id qkmvppvt --num_candidates 8 --achievable_guidance
# Mixed            N=16  DIFF-SA       <- gcbfplus-stl-test/9p02s9ip commit 8499d431 2026-07-06  (success=85.6 plan=0.93s TtR=1516)
run random_loc 9p02s9ip -- --path ./pretrained/DubinsCar/gcbf+/ --area-size 6 --obs 0 --nojit-rollout --spec-len 15 --goal-sample-interval 20 --async-planner --ignore-on-finish --no-video --log --random-goals --traced-goals --change_goal_immediately --epi 10 -n 16 --spec mseq3-m2branch2-mcover3-m2loop3-m2signal3 --planner diffusion --diffusion-method edm --wandb-run-id qkmvppvt
# Mixed            N=16  STLPY-SA      <- gcbfplus-stl-test/9cvow5t8 commit 8499d431 2026-07-05  (success=83.1 plan=25.66s TtR=826)
run random_loc 9cvow5t8 -- --path ./pretrained/DubinsCar/gcbf+/ --area-size 6 --obs 0 --nojit-rollout --spec-len 15 --goal-sample-interval 20 --async-planner --ignore-on-finish --no-video --log --random-goals --traced-goals --change_goal_immediately --epi 10 -n 16 --spec mseq3-m2branch2-mcover3-m2loop3-m2signal3 --planner stlpy
# Mixed            N=16  Gradient      <- diff-mastl-test/vdbub9zk commit 0274dda0 2026-07-06  (success=13.8 plan=63.21s TtR=1706)
#   NOT RUN (ce_nl not in pinned code; bar drawn from manifest ref values):
#   run random_loc vdbub9zk -- --path ./pretrained/DubinsCar/gcbf+/ --epi 5 --area-size 6 --obs 0 --seed 1234 --nojit-rollout --spec-len 30 --goal-sample-interval 20 --async-planner --ignore-on-finish --no-video --log -n 16 --spec mseq3-m2branch2-mcover3-m2loop3-m2signal3 --planner ce_nl --random-goals
# Mixed            N=32  DIFF-MA       <- gcbfplus-stl-test/5dk37krr commit 8499d431 2026-07-05  (success=85.6 plan=1.04s TtR=1891)
run random_loc 5dk37krr -- --path ./pretrained/DubinsCar/gcbf+/ --area-size 6 --obs 0 --nojit-rollout --spec-len 15 --goal-sample-interval 20 --async-planner --ignore-on-finish --no-video --log --random-goals --traced-goals --change_goal_immediately --epi 10 -n 32 --spec mseq3-m2branch2-mcover3-m2loop3-m2signal3 --planner diffusion --diffusion-method edm-ma --wandb-run-id qkmvppvt --num_candidates 8
# Mixed            N=32  DIFF-SA       <- gcbfplus-stl-test/zfckgoch commit 8499d431 2026-07-06  (success=72.2 plan=1.20s TtR=1800)
run random_loc zfckgoch -- --path ./pretrained/DubinsCar/gcbf+/ --area-size 6 --obs 0 --nojit-rollout --spec-len 15 --goal-sample-interval 20 --async-planner --ignore-on-finish --no-video --log --random-goals --traced-goals --change_goal_immediately --epi 10 -n 32 --spec mseq3-m2branch2-mcover3-m2loop3-m2signal3 --planner diffusion --diffusion-method edm --wandb-run-id qkmvppvt
# Mixed            N=32  STLPY-SA      <- gcbfplus-stl-test/f3ajsd2t commit 8499d431 2026-07-05  (success=59.7 plan=48.29s TtR=1147)
run random_loc f3ajsd2t -- --path ./pretrained/DubinsCar/gcbf+/ --area-size 6 --obs 0 --nojit-rollout --spec-len 15 --goal-sample-interval 20 --async-planner --ignore-on-finish --no-video --log --random-goals --traced-goals --change_goal_immediately --epi 10 -n 32 --spec mseq3-m2branch2-mcover3-m2loop3-m2signal3 --planner stlpy
# Mixed            N=32  Gradient      <- diff-mastl-test/abrttvsv commit 0274dda0 2026-07-06  (success=8.8 plan=124.53s TtR=1882)
#   NOT RUN (ce_nl not in pinned code; bar drawn from manifest ref values):
#   run random_loc abrttvsv -- --path ./pretrained/DubinsCar/gcbf+/ --epi 5 --area-size 6 --obs 0 --seed 1234 --nojit-rollout --spec-len 30 --goal-sample-interval 20 --async-planner --ignore-on-finish --no-video --log -n 32 --spec mseq3-m2branch2-mcover3-m2loop3-m2signal3 --planner ce_nl --random-goals
# Seq.             N=8   DIFF-MA       <- gcbfplus-stl-test/gci4sbww commit 8499d431 2026-07-05  (success=100.0 plan=0.17s TtR=1416)
run random_loc gci4sbww -- --path ./pretrained/DubinsCar/gcbf+/ --area-size 6 --obs 0 --nojit-rollout --spec-len 15 --goal-sample-interval 20 --async-planner --ignore-on-finish --no-video --log --random-goals --traced-goals --change_goal_immediately --epi 10 -n 8 --spec mseq3 --planner diffusion --diffusion-method edm-ma --wandb-run-id qkmvppvt --num_candidates 8
# Seq.             N=8   DIFF-SA       <- gcbfplus-stl-test/rehbuox2 commit 8499d431 2026-07-06  (success=97.5 plan=0.33s TtR=1343)
run random_loc rehbuox2 -- --path ./pretrained/DubinsCar/gcbf+/ --area-size 6 --obs 0 --nojit-rollout --spec-len 15 --goal-sample-interval 20 --async-planner --ignore-on-finish --no-video --log --random-goals --traced-goals --change_goal_immediately --epi 10 -n 8 --spec mseq3 --planner diffusion --diffusion-method edm --wandb-run-id qkmvppvt --use_batched_sampling --num_candidates 8
# Seq.             N=8   STLPY-SA      <- gcbfplus-stl-test/u4qpq6ki commit 8499d431 2026-07-05  (success=90.0 plan=3.85s TtR=722)
run random_loc u4qpq6ki -- --path ./pretrained/DubinsCar/gcbf+/ --area-size 6 --obs 0 --nojit-rollout --spec-len 15 --goal-sample-interval 20 --async-planner --ignore-on-finish --no-video --log --random-goals --traced-goals --change_goal_immediately --epi 10 -n 8 --spec mseq3 --planner stlpy
# Seq.             N=8   Gradient      <- diff-mastl-test/kgag2zu3 commit 0274dda0 2026-07-06  (success=25.0 plan=15.44s TtR=1256)
#   NOT RUN (ce_nl not in pinned code; bar drawn from manifest ref values):
#   run random_loc kgag2zu3 -- --path ./pretrained/DubinsCar/gcbf+/ --epi 5 --area-size 6 --obs 0 --seed 1234 --nojit-rollout --spec-len 30 --goal-sample-interval 20 --async-planner --ignore-on-finish --no-video --log -n 8 --spec mseq3 --planner ce_nl --random-goals
# Seq.             N=16  DIFF-MA       <- gcbfplus-stl-test/pmi5efkk commit 8499d431 2026-07-05  (success=100.0 plan=0.18s TtR=1522)
run random_loc pmi5efkk -- --path ./pretrained/DubinsCar/gcbf+/ --area-size 6 --obs 0 --nojit-rollout --spec-len 15 --goal-sample-interval 20 --async-planner --ignore-on-finish --no-video --log --random-goals --traced-goals --change_goal_immediately --epi 10 -n 16 --spec mseq3 --planner diffusion --diffusion-method edm-ma --wandb-run-id qkmvppvt --num_candidates 8
# Seq.             N=16  DIFF-SA       <- gcbfplus-stl-test/jg4at8e3 commit 8499d431 2026-07-06  (success=98.1 plan=0.43s TtR=1514)
run random_loc jg4at8e3 -- --path ./pretrained/DubinsCar/gcbf+/ --area-size 6 --obs 0 --nojit-rollout --spec-len 15 --goal-sample-interval 20 --async-planner --ignore-on-finish --no-video --log --random-goals --traced-goals --change_goal_immediately --epi 10 -n 16 --spec mseq3 --planner diffusion --diffusion-method edm --wandb-run-id qkmvppvt --use_batched_sampling --num_candidates 8
# Seq.             N=16  STLPY-SA      <- gcbfplus-stl-test/7mkeo51j commit 8499d431 2026-07-05  (success=84.4 plan=7.58s TtR=775)
run random_loc 7mkeo51j -- --path ./pretrained/DubinsCar/gcbf+/ --area-size 6 --obs 0 --nojit-rollout --spec-len 15 --goal-sample-interval 20 --async-planner --ignore-on-finish --no-video --log --random-goals --traced-goals --change_goal_immediately --epi 10 -n 16 --spec mseq3 --planner stlpy
# Seq.             N=16  Gradient      <- diff-mastl-test/5t78ytkj commit 0274dda0 2026-07-06  (success=25.0 plan=32.71s TtR=1404)
#   NOT RUN (ce_nl not in pinned code; bar drawn from manifest ref values):
#   run random_loc 5t78ytkj -- --path ./pretrained/DubinsCar/gcbf+/ --epi 5 --area-size 6 --obs 0 --seed 1234 --nojit-rollout --spec-len 30 --goal-sample-interval 20 --async-planner --ignore-on-finish --no-video --log -n 16 --spec mseq3 --planner ce_nl --random-goals
# Seq.             N=32  DIFF-MA       <- gcbfplus-stl-test/2uty9yp3 commit 8499d431 2026-07-05  (success=92.2 plan=0.20s TtR=1841)
run random_loc 2uty9yp3 -- --path ./pretrained/DubinsCar/gcbf+/ --area-size 6 --obs 0 --nojit-rollout --spec-len 15 --goal-sample-interval 20 --async-planner --ignore-on-finish --no-video --log --random-goals --traced-goals --change_goal_immediately --epi 10 -n 32 --spec mseq3 --planner diffusion --diffusion-method edm-ma --wandb-run-id qkmvppvt --num_candidates 8
# Seq.             N=32  DIFF-SA       <- gcbfplus-stl-test/vn82y76w commit 8499d431 2026-07-06  (success=85.3 plan=0.68s TtR=1783)
run random_loc vn82y76w -- --path ./pretrained/DubinsCar/gcbf+/ --area-size 6 --obs 0 --nojit-rollout --spec-len 15 --goal-sample-interval 20 --async-planner --ignore-on-finish --no-video --log --random-goals --traced-goals --change_goal_immediately --epi 10 -n 32 --spec mseq3 --planner diffusion --diffusion-method edm --wandb-run-id qkmvppvt --use_batched_sampling --num_candidates 8
# Seq.             N=32  STLPY-SA      <- gcbfplus-stl-test/2l9fp8se commit 8499d431 2026-07-05  (success=63.7 plan=15.40s TtR=1118)
run random_loc 2l9fp8se -- --path ./pretrained/DubinsCar/gcbf+/ --area-size 6 --obs 0 --nojit-rollout --spec-len 15 --goal-sample-interval 20 --async-planner --ignore-on-finish --no-video --log --random-goals --traced-goals --change_goal_immediately --epi 10 -n 32 --spec mseq3 --planner stlpy
# Seq.             N=32  Gradient      <- diff-mastl-test/ufzwjfb6 commit 0274dda0 2026-07-06  (success=16.2 plan=69.43s TtR=1738)
#   NOT RUN (ce_nl not in pinned code; bar drawn from manifest ref values):
#   run random_loc ufzwjfb6 -- --path ./pretrained/DubinsCar/gcbf+/ --epi 5 --area-size 6 --obs 0 --seed 1234 --nojit-rollout --spec-len 30 --goal-sample-interval 20 --async-planner --ignore-on-finish --no-video --log -n 32 --spec mseq3 --planner ce_nl --random-goals
# Signal           N=8   DIFF-MA       <- gcbfplus-stl-test/w88kqu0o commit 28eddb81 2026-07-11  (success=97.5 plan=0.58s TtR=1802)
run random_loc w88kqu0o -- --path ./pretrained/DubinsCar/gcbf+/ --epi 10 --area-size 6 --obs 0 --nojit-rollout --spec m2signal3 --spec-len 15 --goal-sample-interval 20 --async-planner --ignore-on-finish --no-video --log --change_goal_immediately --random-goals --traced-goals --random-goals-spacing 2.0 --stl_mixed_spec_mode None -n 8 --planner diffusion --diffusion-method edm-ma --wandb-run-id qkmvppvt --num_candidates 8 --random-goals-region 1.5
# Signal           N=8   DIFF-SA       <- gcbfplus-stl-test/f39mseae commit 28eddb81 2026-07-11  (success=97.5 plan=0.64s TtR=1701)
run random_loc f39mseae -- --path ./pretrained/DubinsCar/gcbf+/ --epi 10 --area-size 6 --obs 0 --nojit-rollout --spec m2signal3 --spec-len 15 --goal-sample-interval 20 --async-planner --ignore-on-finish --no-video --log --change_goal_immediately --random-goals --traced-goals --random-goals-spacing 2.0 --stl_mixed_spec_mode None -n 8 --planner diffusion --diffusion-method edm --wandb-run-id qkmvppvt --random-goals-region 1.5
# Signal           N=8   STLPY-SA      <- gcbfplus-stl-test/yxl6715l commit 28eddb81 2026-07-11  (success=91.2 plan=20.23s TtR=1030)
run random_loc yxl6715l -- --path ./pretrained/DubinsCar/gcbf+/ --epi 10 --area-size 6 --obs 0 --nojit-rollout --spec m2signal3 --spec-len 15 --goal-sample-interval 20 --async-planner --ignore-on-finish --no-video --log --change_goal_immediately --random-goals --traced-goals --random-goals-spacing 2.0 --stl_mixed_spec_mode None -n 8 --planner stlpy --random-goals-region 1.5
# Signal           N=8   Gradient      <- diff-mastl-test/4rf7k5mj commit 0274dda0 2026-07-06  (success=7.5 plan=66.55s TtR=1978)
#   NOT RUN (ce_nl not in pinned code; bar drawn from manifest ref values):
#   run random_loc 4rf7k5mj -- --path ./pretrained/DubinsCar/gcbf+/ --epi 5 --area-size 6 --obs 0 --seed 1234 --nojit-rollout --spec-len 30 --goal-sample-interval 20 --async-planner --ignore-on-finish --no-video --log -n 8 --spec m2signal3 --planner ce_nl --random-goals --random-goals-spacing 2
# Signal           N=16  DIFF-MA       <- gcbfplus-stl-test/cuaaektp commit 28eddb81 2026-07-11  (success=92.5 plan=0.72s TtR=1905)
run random_loc cuaaektp -- --path ./pretrained/DubinsCar/gcbf+/ --epi 10 --area-size 6 --obs 0 --nojit-rollout --spec m2signal3 --spec-len 15 --goal-sample-interval 20 --async-planner --ignore-on-finish --no-video --log --change_goal_immediately --random-goals --traced-goals --random-goals-spacing 2.0 --stl_mixed_spec_mode None -n 16 --planner diffusion --diffusion-method edm-ma --wandb-run-id qkmvppvt --num_candidates 8 --random-goals-region 1.5
# Signal           N=16  DIFF-SA       <- gcbfplus-stl-test/rxdiagvs commit 28eddb81 2026-07-11  (success=90.6 plan=0.73s TtR=1970)
run random_loc rxdiagvs -- --path ./pretrained/DubinsCar/gcbf+/ --epi 10 --area-size 6 --obs 0 --nojit-rollout --spec m2signal3 --spec-len 15 --goal-sample-interval 20 --async-planner --ignore-on-finish --no-video --log --change_goal_immediately --random-goals --traced-goals --random-goals-spacing 2.0 --stl_mixed_spec_mode None -n 16 --planner diffusion --diffusion-method edm --wandb-run-id qkmvppvt --random-goals-region 1.5
# Signal           N=16  STLPY-SA      <- gcbfplus-stl-test/bybo5u0o commit 28eddb81 2026-07-11  (success=92.5 plan=41.39s TtR=1168)
run random_loc bybo5u0o -- --path ./pretrained/DubinsCar/gcbf+/ --epi 10 --area-size 6 --obs 0 --nojit-rollout --spec m2signal3 --spec-len 15 --goal-sample-interval 20 --async-planner --ignore-on-finish --no-video --log --change_goal_immediately --random-goals --traced-goals --random-goals-spacing 2.0 --stl_mixed_spec_mode None -n 16 --planner stlpy --random-goals-region 1.5
# Signal           N=16  Gradient      <- diff-mastl-test/wpwgnkz5 commit 0274dda0 2026-07-06  (success=10.0 plan=142.00s TtR=2006)
#   NOT RUN (ce_nl not in pinned code; bar drawn from manifest ref values):
#   run random_loc wpwgnkz5 -- --path ./pretrained/DubinsCar/gcbf+/ --epi 5 --area-size 6 --obs 0 --seed 1234 --nojit-rollout --spec-len 30 --goal-sample-interval 20 --async-planner --ignore-on-finish --no-video --log -n 16 --spec m2signal3 --planner ce_nl --random-goals --random-goals-spacing 2
# Signal           N=32  DIFF-MA       <- gcbfplus-stl-test/drgx6qov commit 8499d431 2026-07-05  (success=89.1 plan=0.90s TtR=2275)
run random_loc drgx6qov -- --path ./pretrained/DubinsCar/gcbf+/ --area-size 6 --obs 0 --nojit-rollout --spec-len 15 --goal-sample-interval 20 --async-planner --ignore-on-finish --no-video --log --random-goals --traced-goals --change_goal_immediately --epi 10 -n 32 --spec m2signal3 --random-goals-spacing 2.0 --random-goals-region 1.5 --planner diffusion --diffusion-method edm-ma --wandb-run-id qkmvppvt --num_candidates 8
# Signal           N=32  DIFF-SA       <- gcbfplus-stl-test/a3312mf1 commit 8499d431 2026-07-06  (success=84.1 plan=1.75s TtR=2342)
run random_loc a3312mf1 -- --path ./pretrained/DubinsCar/gcbf+/ --area-size 6 --obs 0 --nojit-rollout --spec-len 15 --goal-sample-interval 20 --async-planner --ignore-on-finish --no-video --log --random-goals --traced-goals --change_goal_immediately --epi 10 -n 32 --spec m2signal3 --random-goals-spacing 2.0 --random-goals-region 1.5 --planner diffusion --diffusion-method edm --wandb-run-id qkmvppvt --use_batched_sampling --num_candidates 8
# Signal           N=32  STLPY-SA      <- gcbfplus-stl-test/ytq1lt14 commit 8499d431 2026-07-05  (success=78.8 plan=78.60s TtR=1429)
run random_loc ytq1lt14 -- --path ./pretrained/DubinsCar/gcbf+/ --area-size 6 --obs 0 --nojit-rollout --spec-len 15 --goal-sample-interval 20 --async-planner --ignore-on-finish --no-video --log --random-goals --traced-goals --change_goal_immediately --epi 10 -n 32 --spec m2signal3 --random-goals-spacing 2.0 --random-goals-region 1.5 --planner stlpy
# Signal           N=32  Gradient      <- diff-mastl-test/z2rq11nf commit 0274dda0 2026-07-06  (success=7.5 plan=296.21s TtR=2260)
#   NOT RUN (ce_nl not in pinned code; bar drawn from manifest ref values):
#   run random_loc z2rq11nf -- --path ./pretrained/DubinsCar/gcbf+/ --epi 5 --area-size 6 --obs 0 --seed 1234 --nojit-rollout --spec-len 30 --goal-sample-interval 20 --async-planner --ignore-on-finish --no-video --log -n 32 --spec m2signal3 --planner ce_nl --random-goals --random-goals-spacing 2

# ================================================================================================
# FIGURE team_spec  (scripts/plot_team_spec_results.py --merge-edm --show-global, scope=emergent)
# area-6, epi 10, max-step 7200, team-avoid; DIFF-MA = emergent (team-disjunctive) edm-ma; Choice N=32
# DIFF-MA uses GCBF_GOAL_SCALE=1.25 decongestion. STLPY-SA rows: see KNOWN LIMITS.
# ================================================================================================
# Choice ($\vee$)  N=8   DIFF-MA       <- gcbfplus-stl-test/2muf7mmu commit 00700381 2026-07-12  (success=100.0 plan=0.60s TtR=1706)
run team_spec 2muf7mmu GCBF_TEAM_SELECT_OUTER=1 -- --path ./pretrained/DubinsCar/gcbf+/ --epi 10 --area-size 6 --max-step 7200 --obs 0 --nojit-rollout --spec team_choiceseq3 --spec-len 15 --goal-sample-interval 20 --async-planner --ignore-on-finish --no-video --log --change_goal_immediately --team-avoid --use_batched_sampling -n 8 --planner diffusion --diffusion-method edm-ma --wandb-run-id qkmvppvt --team-disjunctive --num_candidates 8
# Choice ($\vee$)  N=8   STLPY-SA      <- old local test_log.csv (no W&B run) -- BEST-EFFORT reconstruction  (success=92.5 plan=5.39s TtR=1308)
run team_spec local_choice_N8 -- --path ./pretrained/DubinsCar/gcbf+/ --epi 10 --area-size 6 --max-step 2400 --obs 0 --nojit-rollout --spec-len 15 --goal-sample-interval 20 --async-planner --ignore-on-finish --no-video --log --change_goal_immediately --team-avoid -n 8 --spec team_choiceseq3_t15 --planner stlpy --team-alloc greedy --stl_mixed_spec_mode first1
# Choice ($\vee$)  N=8   STLPY-Global  <- gcbfplus-stl-test/4lozy92j commit d7f73603 2026-07-12  (success=58.1 plan=832.30s TtR=973)
run team_spec 4lozy92j GCBF_TEAM_SELECT_OUTER=0 -- --path ./pretrained/DubinsCar/gcbf+/ --epi 10 --area-size 6 --max-step 7200 --obs 0 --nojit-rollout --spec-len 15 --goal-sample-interval 20 --async-planner --ignore-on-finish --no-video --log --change_goal_immediately --team-avoid -n 8 --spec team_choiceseq3 --planner stlpy_global
# Choice ($\vee$)  N=16  DIFF-MA       <- gcbfplus-stl-test/tk5zcwmj commit 0281b5d1 2026-07-12  (success=98.8 plan=12.02s TtR=1845)
run team_spec tk5zcwmj GCBF_TEAM_SELECT_OUTER=1 -- --path ./pretrained/DubinsCar/gcbf+/ --epi 10 -n 16 --area-size 6 --max-step 7200 --obs 0 --nojit-rollout --spec team_choiceseq3 --spec-len 15 --goal-sample-interval 20 --async-planner --ignore-on-finish --no-video --log --change_goal_immediately --team-disjunctive --team-avoid --use_batched_sampling --num_candidates 16 --planner diffusion --diffusion-method edm-ma --wandb-run-id qkmvppvt
# Choice ($\vee$)  N=16  STLPY-SA      <- old local test_log.csv (no W&B run) -- BEST-EFFORT reconstruction  (success=68.8 plan=10.38s TtR=1550)
run team_spec local_choice_N16 -- --path ./pretrained/DubinsCar/gcbf+/ --epi 10 --area-size 6 --max-step 2700 --obs 0 --nojit-rollout --spec-len 15 --goal-sample-interval 20 --async-planner --ignore-on-finish --no-video --log --change_goal_immediately --team-avoid -n 16 --spec team_choiceseq3_t15 --planner stlpy --team-alloc greedy --stl_mixed_spec_mode first1
# Choice ($\vee$)  N=32  DIFF-MA       <- gcbfplus-stl-test/k8kfrm63 commit d44d8acf 2026-07-12  (success=76.2 plan=2.91s TtR=2448)
run team_spec k8kfrm63 GCBF_GOAL_SCALE=1.25 GCBF_TEAM_SELECT_OUTER=1 -- --path ./pretrained/DubinsCar/gcbf+/ --epi 10 -n 32 --area-size 6 --max-step 7200 --obs 0 --nojit-rollout --spec team_choiceseq3 --spec-len 15 --goal-sample-interval 20 --async-planner --ignore-on-finish --no-video --log --change_goal_immediately --team-avoid --use_batched_sampling --planner diffusion --diffusion-method edm-ma --wandb-run-id qkmvppvt --team-disjunctive --num_candidates 16
# Choice ($\vee$)  N=32  STLPY-SA      <- old local test_log.csv (no W&B run) -- BEST-EFFORT reconstruction  (success=41.7 plan=20.77s TtR=1959)
run team_spec local_choice_N32 -- --path ./pretrained/DubinsCar/gcbf+/ --epi 10 --area-size 6 --max-step 3600 --obs 0 --nojit-rollout --spec-len 15 --goal-sample-interval 20 --async-planner --ignore-on-finish --no-video --log --change_goal_immediately --team-avoid -n 32 --spec team_choiceseq3_t15 --planner stlpy --team-alloc greedy --stl_mixed_spec_mode first1
# Redundant ($\wedge$) N=8   DIFF-MA       <- gcbfplus-stl-test/kxfnwm84 commit 28eddb81 2026-07-11  (success=100.0 plan=2.07s TtR=1416)
run team_spec kxfnwm84 -- --path ./pretrained/DubinsCar/gcbf+/ --epi 10 --area-size 6 --max-step 7200 --obs 0 --nojit-rollout --spec-len 15 --goal-sample-interval 20 --async-planner --ignore-on-finish --no-video --log --change_goal_immediately --team-avoid --use_batched_sampling --num_candidates 8 -n 8 --planner diffusion --diffusion-method edm-ma --wandb-run-id qkmvppvt --spec team_redun4x2 --team-disjunctive
# Redundant ($\wedge$) N=8   STLPY-SA      <- old local test_log.csv (no W&B run) -- BEST-EFFORT reconstruction  (success=100.0 plan=8.13s TtR=683)
run team_spec local_redund_N8 -- --path ./pretrained/DubinsCar/gcbf+/ --epi 5 --area-size 6 --max-step 900 --obs 0 --nojit-rollout --spec-len 15 --goal-sample-interval 20 --async-planner --ignore-on-finish --no-video --log --change_goal_immediately --team-avoid -n 8 --spec team_redun4x2_t15 --planner stlpy --team-alloc greedy --stl_mixed_spec_mode first1
# Redundant ($\wedge$) N=8   STLPY-Global  <- gcbfplus-stl-test/3zg26ley commit d7f73603 2026-07-12  (success=100.0 plan=778.45s TtR=561)
run team_spec 3zg26ley GCBF_TEAM_SELECT_OUTER=0 -- --path ./pretrained/DubinsCar/gcbf+/ --epi 10 --area-size 6 --max-step 7200 --obs 0 --nojit-rollout --spec-len 15 --goal-sample-interval 20 --async-planner --ignore-on-finish --no-video --log --change_goal_immediately --team-avoid -n 8 --spec team_redun4x2 --planner stlpy_global
# Redundant ($\wedge$) N=16  DIFF-MA       <- gcbfplus-stl-test/jn3dp66b commit 28eddb81 2026-07-11  (success=100.0 plan=5.64s TtR=1468)
run team_spec jn3dp66b -- --path ./pretrained/DubinsCar/gcbf+/ --epi 10 --area-size 6 --max-step 7200 --obs 0 --nojit-rollout --spec-len 15 --goal-sample-interval 20 --async-planner --ignore-on-finish --no-video --log --change_goal_immediately --team-avoid --use_batched_sampling --num_candidates 8 -n 16 --planner diffusion --diffusion-method edm-ma --wandb-run-id qkmvppvt --spec team_redun4x4 --team-disjunctive
# Redundant ($\wedge$) N=16  STLPY-SA      <- old local test_log.csv (no W&B run) -- BEST-EFFORT reconstruction  (success=98.8 plan=11.27s TtR=757)
run team_spec local_redund_N16 -- --path ./pretrained/DubinsCar/gcbf+/ --epi 5 --area-size 6 --max-step 1200 --obs 0 --nojit-rollout --spec-len 15 --goal-sample-interval 20 --async-planner --ignore-on-finish --no-video --log --change_goal_immediately --team-avoid -n 16 --spec team_redun4x4_t15 --planner stlpy --team-alloc greedy --stl_mixed_spec_mode first1
# Redundant ($\wedge$) N=32  DIFF-MA       <- gcbfplus-stl-test/ry1xtsxy commit 155cf85a 2026-07-03  (success=94.7 plan=10.76s TtR=1512)
run team_spec ry1xtsxy -- --path ./pretrained/DubinsCar/gcbf+/ --epi 10 --area-size 6 -n 32 --obs 0 --nojit-rollout --spec-len 15 --goal-sample-interval 20 --async-planner --ignore-on-finish --no-video --log --max-step 7200 --change_goal_immediately --team-avoid --planner diffusion --diffusion-method edm-ma --wandb-run-id qkmvppvt --use_batched_sampling --num_candidates 8 --team-disjunctive --spec team_redun4x8
# Redundant ($\wedge$) N=32  STLPY-SA      <- old local test_log.csv (no W&B run) -- BEST-EFFORT reconstruction  (success=68.4 plan=32.57s TtR=858)
run team_spec local_redund_N32 -- --path ./pretrained/DubinsCar/gcbf+/ --epi 5 --area-size 6 --max-step 1500 --obs 0 --nojit-rollout --spec-len 15 --goal-sample-interval 20 --async-planner --ignore-on-finish --no-video --log --change_goal_immediately --team-avoid -n 32 --spec team_redun4x8_t15 --planner stlpy --team-alloc greedy --stl_mixed_spec_mode first1

# ================================================================================================
# FIGURE high_n  (scripts/plot_high_n_scaling.py)
# Mixed spec mseq3-m2branch2-mcover3-m2loop3-m2signal3. success panel: native area-6/epi-10 at N<=32,
# GCBF_GOAL_SCALE=2.0/area-10/epi-3 at N>=64. TtR + plan-time panels: the gs2.0 run at EVERY N.
# ================================================================================================
# Mixed            N=8   DIFF-MA      [success panel]  <- diff-mastl-test/f5d2gd50 commit 5227c2d0 2026-06-23  (success=100.0 plan=29.03s TtR=1750)
run high_n f5d2gd50 -- --path ./pretrained/DubinsCar/gcbf+/ --epi 10 --area-size 6 --obs 0 --seed 1234 --nojit-rollout --spec-len 15 --goal-sample-interval 20 --async-planner --ignore-on-finish --no-video --log -n 8 --spec mseq3-m2branch2-mcover3-m2loop3-m2signal3 --planner diffusion --diffusion-method edm-ma --use_batched_sampling --num_candidates 8 --wandb-run-id qkmvppvt --change_goal_immediately --stl_mixed_spec_mode first1
# Mixed            N=8   DIFF-MA      [timing panel]  <- diff-mastl-test/f0td1sgv commit 2d6867f6 2026-06-25  (success=91.7 plan=3.49s TtR=2424)
run high_n f0td1sgv GCBF_GOAL_SCALE=2 -- --path ./pretrained/DubinsCar/gcbf+/ --epi 3 --area-size 10 --obs 0 --nojit-rollout --spec-len 15 --goal-sample-interval 20 --spec mseq3-m2branch2-mcover3-m2loop3-m2signal3 --async-planner --ignore-on-finish --no-video --log -n 8 --planner diffusion --diffusion-method edm-ma --wandb-run-id qkmvppvt --num_candidates 8
# Mixed            N=8   STLPY-SA     [success panel]  <- diff-mastl-test/j8ok65qr commit 5227c2d0 2026-06-23  (success=95.0 plan=6.08s TtR=1539)
run high_n j8ok65qr -- --path ./pretrained/DubinsCar/gcbf+/ --epi 10 --area-size 6 --obs 0 --seed 1234 --nojit-rollout --spec-len 15 --goal-sample-interval 20 --async-planner --ignore-on-finish --no-video --log -n 8 --spec mseq3-m2branch2-mcover3-m2loop3-m2signal3 --planner stlpy --team-alloc greedy --stl_mixed_spec_mode first1
# Mixed            N=8   STLPY-SA     [timing panel]  <- diff-mastl-test/gh5zqw36 commit 2d6867f6 2026-06-25  (success=58.3 plan=12.39s TtR=1441)
run high_n gh5zqw36 GCBF_GOAL_SCALE=2 -- --path ./pretrained/DubinsCar/gcbf+/ --epi 3 --area-size 10 --obs 0 --nojit-rollout --spec-len 15 --goal-sample-interval 20 --spec mseq3-m2branch2-mcover3-m2loop3-m2signal3 --async-planner --ignore-on-finish --no-video --log -n 8 --planner stlpy --team-alloc greedy
# Mixed            N=16  DIFF-MA      [success panel]  <- diff-mastl-test/rceicdzr commit 5227c2d0 2026-06-23  (success=98.8 plan=25.19s TtR=1795)
run high_n rceicdzr -- --path ./pretrained/DubinsCar/gcbf+/ --epi 10 --area-size 6 --obs 0 --seed 1234 --nojit-rollout --spec-len 15 --goal-sample-interval 20 --async-planner --ignore-on-finish --no-video --log -n 16 --spec mseq3-m2branch2-mcover3-m2loop3-m2signal3 --planner diffusion --diffusion-method edm-ma --use_batched_sampling --num_candidates 8 --wandb-run-id qkmvppvt --change_goal_immediately --stl_mixed_spec_mode first1
# Mixed            N=16  DIFF-MA      [timing panel]  <- diff-mastl-test/kert91iv commit 2d6867f6 2026-06-25  (success=91.7 plan=6.18s TtR=2513)
run high_n kert91iv GCBF_GOAL_SCALE=2 -- --path ./pretrained/DubinsCar/gcbf+/ --epi 3 --area-size 10 --obs 0 --nojit-rollout --spec-len 15 --goal-sample-interval 20 --spec mseq3-m2branch2-mcover3-m2loop3-m2signal3 --async-planner --ignore-on-finish --no-video --log -n 16 --planner diffusion --diffusion-method edm-ma --wandb-run-id qkmvppvt --num_candidates 8
# Mixed            N=16  STLPY-SA     [success panel]  <- diff-mastl-test/e6x94wxf commit 5227c2d0 2026-06-23  (success=90.0 plan=20.41s TtR=1173)
run high_n e6x94wxf -- --path ./pretrained/DubinsCar/gcbf+/ --epi 10 --area-size 6 --obs 0 --seed 1234 --nojit-rollout --spec-len 15 --goal-sample-interval 20 --async-planner --ignore-on-finish --no-video --log -n 16 --spec mseq3-m2branch2-mcover3-m2loop3-m2signal3 --planner stlpy --team-alloc greedy --change_goal_immediately --stl_mixed_spec_mode first1
# Mixed            N=16  STLPY-SA     [timing panel]  <- diff-mastl-test/6gn8oe9k commit 2d6867f6 2026-06-25  (success=64.6 plan=25.26s TtR=1596)
run high_n 6gn8oe9k GCBF_GOAL_SCALE=2 -- --path ./pretrained/DubinsCar/gcbf+/ --epi 3 --area-size 10 --obs 0 --nojit-rollout --spec-len 15 --goal-sample-interval 20 --spec mseq3-m2branch2-mcover3-m2loop3-m2signal3 --async-planner --ignore-on-finish --no-video --log -n 16 --planner stlpy --team-alloc greedy
# Mixed            N=32  DIFF-MA      [success panel]  <- diff-mastl-test/dn6gmrhl commit 5227c2d0 2026-06-23  (success=91.6 plan=19.59s TtR=2036)
run high_n dn6gmrhl -- --path ./pretrained/DubinsCar/gcbf+/ --epi 10 --area-size 6 --obs 0 --seed 1234 --nojit-rollout --spec-len 15 --goal-sample-interval 20 --async-planner --ignore-on-finish --no-video --log -n 32 --spec mseq3-m2branch2-mcover3-m2loop3-m2signal3 --planner diffusion --diffusion-method edm-ma --use_batched_sampling --num_candidates 8 --resample_batch_size 8 --wandb-run-id qkmvppvt --change_goal_immediately --stl_mixed_spec_mode first1
# Mixed            N=32  DIFF-MA      [timing panel]  <- diff-mastl-test/ietvs4pq commit 2d6867f6 2026-06-25  (success=89.6 plan=7.90s TtR=2699)
run high_n ietvs4pq GCBF_GOAL_SCALE=2 -- --path ./pretrained/DubinsCar/gcbf+/ --epi 3 --area-size 10 --obs 0 --nojit-rollout --spec-len 15 --goal-sample-interval 20 --spec mseq3-m2branch2-mcover3-m2loop3-m2signal3 --async-planner --ignore-on-finish --no-video --log -n 32 --planner diffusion --diffusion-method edm-ma --wandb-run-id qkmvppvt --num_candidates 8
# Mixed            N=32  STLPY-SA     [success panel]  <- diff-mastl-test/wz08w5bw commit 5227c2d0 2026-06-23  (success=81.9 plan=55.81s TtR=1626)
run high_n wz08w5bw -- --path ./pretrained/DubinsCar/gcbf+/ --epi 10 --area-size 6 --obs 0 --seed 1234 --nojit-rollout --spec-len 15 --goal-sample-interval 20 --async-planner --ignore-on-finish --no-video --log -n 32 --spec mseq3-m2branch2-mcover3-m2loop3-m2signal3 --planner stlpy --team-alloc greedy --stl_mixed_spec_mode None
# Mixed            N=32  STLPY-SA     [timing panel]  <- diff-mastl-test/sa5tmyv6 commit 2d6867f6 2026-06-25  (success=66.7 plan=46.19s TtR=1808)
run high_n sa5tmyv6 GCBF_GOAL_SCALE=2 -- --path ./pretrained/DubinsCar/gcbf+/ --epi 3 --area-size 10 --obs 0 --nojit-rollout --spec-len 15 --goal-sample-interval 20 --spec mseq3-m2branch2-mcover3-m2loop3-m2signal3 --async-planner --ignore-on-finish --no-video --log -n 32 --planner stlpy --team-alloc greedy
# Mixed            N=64  DIFF-MA       <- diff-mastl-test/sm1rrbw2 commit 2d6867f6 2026-06-25  (success=70.8 plan=20.94s TtR=3150)
run high_n sm1rrbw2 GCBF_GOAL_SCALE=2 -- --path ./pretrained/DubinsCar/gcbf+/ --epi 3 --area-size 10 --obs 0 --nojit-rollout --spec-len 15 --goal-sample-interval 20 --spec mseq3-m2branch2-mcover3-m2loop3-m2signal3 --async-planner --ignore-on-finish --no-video --log -n 64 --planner diffusion --diffusion-method edm-ma --wandb-run-id qkmvppvt --num_candidates 8
# Mixed            N=64  STLPY-SA      <- diff-mastl-test/n8japtot commit 2d6867f6 2026-06-25  (success=55.2 plan=90.96s TtR=1835)
run high_n n8japtot GCBF_GOAL_SCALE=2 -- --path ./pretrained/DubinsCar/gcbf+/ --epi 3 --area-size 10 --obs 0 --nojit-rollout --spec-len 15 --goal-sample-interval 20 --spec mseq3-m2branch2-mcover3-m2loop3-m2signal3 --async-planner --ignore-on-finish --no-video --log -n 64 --planner stlpy --team-alloc greedy
# Mixed            N=128 DIFF-MA       <- diff-mastl-test/dhlreotp commit 2d6867f6 2026-06-25  (success=34.4 plan=49.89s TtR=3662)
run high_n dhlreotp GCBF_GOAL_SCALE=2 -- --path ./pretrained/DubinsCar/gcbf+/ --epi 3 --area-size 10 --obs 0 --nojit-rollout --spec-len 15 --goal-sample-interval 20 --spec mseq3-m2branch2-mcover3-m2loop3-m2signal3 --async-planner --ignore-on-finish --no-video --log -n 128 --planner diffusion --diffusion-method edm-ma --wandb-run-id qkmvppvt --num_candidates 8
# Mixed            N=128 STLPY-SA      <- diff-mastl-test/z34c6fg2 commit 2d6867f6 2026-06-25  (success=33.3 plan=195.15s TtR=2265)
run high_n z34c6fg2 GCBF_GOAL_SCALE=2 -- --path ./pretrained/DubinsCar/gcbf+/ --epi 3 --area-size 10 --obs 0 --nojit-rollout --spec-len 15 --goal-sample-interval 20 --spec mseq3-m2branch2-mcover3-m2loop3-m2signal3 --async-planner --ignore-on-finish --no-video --log -n 128 --planner stlpy --team-alloc greedy

echo; echo "==================== summary ===================="
echo "PASS (${#PASS[@]}): ${PASS[*]:-none}"
echo "SKIP (${#SKIP[@]}): ${SKIP[*]:-none}"
echo "FAIL (${#FAIL[@]}): ${FAIL[*]:-none}"
echo "logs in: $LOG_DIR/test_log_repro_<id>.csv   ->   python scripts/release/plot_reproduced.py --out-dir out_repro"
[ "${#FAIL[@]}" -eq 0 ]
